<h1>Numpy</h1>
In this session, we discuss a little about the <a href="http://www.numpy.org/">Numpy</a> library that adds matrix and multi-dimensional array operation in python.

<h3>Import</h3>
Numpy is imported to python using the name 'numpy' and commonly imported in the name 'np'

In [1]:
import numpy as np

<h3>Numpy array</h3>
We can create a numpy array using the np.array() function.

In [5]:
a = np.array([1,2,3,4,5]) 
print a
print type(a)

[1 2 3 4 5]
<type 'numpy.ndarray'>


<h3>Operators</h3>
Lets compare between numpy array and the python list in the different operators used.<br>
<b>1. '+':</b>
    This sign does concatenation for python list and element wise addition for numpy arrays
    

In [6]:
# python list
a = [1,2]
b = [6,7]
print a+b

[1, 2, 6, 7]


In [7]:
# numpy array
a = np.array([1,2])
b = np.array([6,7])
print a+b

[7 9]


Note: <t>As '+' in numpy performs element wise addition / Vector addition, <b>both the numpy arrays</b> need to be of same shape.<br/>
In python list it performs concatenation so the <b>lists can be of different size</b>

In [10]:
a = np.array([1,2,3])
b = np.array([5,6])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
a = [1,2,3]
b = [5,6]
print a+b

[1, 2, 3, 5, 6]


<b>2. * operator:</b>
It does element wise multiplication in numpy arrays while is repeats the list in the case of python list

In [14]:
a = [1,2,3,4]
a*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
a=np.array([1,2,3,4])
a*3

array([ 3,  6,  9, 12])

In [18]:
2*a

array([2, 4, 6, 8])

In [31]:
a*a # Element wise numtiplication

array([1, 4, 9])

<b>3. ** operator</b>
It is the exponentiation operator for numpy arrays

In [23]:
a=np.array([1,2,3,4,5])
a**3

array([  1,   8,  27,  64, 125])

In [24]:
3**a

array([  3,   9,  27,  81, 243])

<h3>Array Operations</h3>
<b>1. Square root, log and exponentiation functions</b>

In [25]:
np.sqrt([1,4,9,16])

array([ 1.,  2.,  3.,  4.])

In [26]:
np.log([1,2,3,4])

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

<b>2. Dot Product</b><br>
=> np.dot(a,b) OR<br>
=> a.dot(b)

In [35]:
a = np.array([1,2])
b = np.array([3,4])
print "a.dot(b) = ", a.dot(b)
print "np.dot(a,b) = ", np.dot(a,b)

a.dot(b) =  11
np.dot(a,b) =  11


<b>3. Sum </b><br>
=> np.sum(a,axis)
If no axis is added, it flattens the array and takes the sum. For axis=0, it returns sum along the column. For axis=1, sum along row is calculated

In [36]:
np.sum([1,2,3,4])

10

In [37]:
a=np.array([
        [1,2,3],
        [1,2,3]
    ])
np.sum(a)

12

In [38]:
np.sum(a,axis=0)

array([2, 4, 6])

In [40]:
np.sum(a, axis=1)

array([6, 6])

<b>4. Norm of a vector</b><br>
np.linalg.norm(a)

In [46]:
a=np.array([
        [1,2,3],
        [1,2,3]
    ])
np.sum(a)

12

In [47]:
np.linalg.norm(a)

5.2915026221291814

In [48]:
np.linalg.norm(a, axis=0)

array([ 1.41421356,  2.82842712,  4.24264069])

In [49]:
np.linalg.norm(a, axis=1)

array([ 3.74165739,  3.74165739])

<b>5. Angle between vectors</b><br>
cosangle = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))<br>
angle = np.arccos(cosangle)

In [56]:
a = np.array([1,2,3])
b = np.array([4,3,2])

In [57]:
cosangle = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))
angle = np.arccos(cosangle)
print angle *(360/(2*3.14)), "degree"

37.4517977747 degree


<h3>Matrices</h3><br>
<b>Create a matrix:</b><br>
np.array([[1,2,3],[2,3,4]])<br><br>
We can either get the element by <b>a[row_index, column_index]</b> OR <b>a[row_index][column_index]</b>

In [58]:
M = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]])

In [59]:
M[0,2]

3

In [61]:
M[0][2]

3

In [62]:
M[1,1]

5

<h3>Create arrays and matrices</h3><br>
<b>1. Create array of zeros</b><br>
np.zeros(shape)

In [63]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [65]:
np.zeros([3,2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

<b>2. Create array of ones</b><br>
np.ones(shape)

In [67]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [68]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<b>3. Create Random Array: Uniformily distributed</b><br>
    np.random.random(shape)

In [69]:
np.random.random([2,3])

array([[ 0.47430601,  0.94318257,  0.19382838],
       [ 0.27328995,  0.78986521,  0.31855438]])

<b>4. Create Random Array: Normally distributed</b><br>
np.random.random(shape)<br>

It will create a gaussian disturbution with mean=0 and standard deviation=1

In [75]:
np.random.randn(2,3)

array([[-0.71760327,  1.44055501, -1.49317794],
       [ 0.49685926, -1.44548218, -1.39147421]])

<b>To find the mean and variance:</b><br>
a.mean(axis)<br>
a.var(axis)

In [86]:
a = np.random.randn(1000,2)
b = np.random.randn(2,1000)
print a.mean()
print a.mean(axis=0)
print b.mean(axis=1)

0.0109308379744
[-0.00252873  0.0243904 ]
[ 0.02837727  0.04294857]


In [87]:
print a.var()
print a.var(axis=0)
print b.var(axis=1)

1.02565581907
[ 1.05553608  0.99541324]
[ 1.01747885  0.99880037]


<h3>Matrix Operations</h3><br>
<b>1. Multiplication</b><br>
We can use the same function as a.dot(b)

In [88]:
a=np.random.randn(2,3)
b=np.random.randn(3,5)
a.dot(b)

array([[ 0.11762771,  0.44673515, -0.21255845, -0.22845007,  0.51280975],
       [-1.50647189,  0.25837157,  1.1205941 ,  0.43469543,  4.93815318]])